<?php

/**
 * Field
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Field extends BaseField {
	
	
	public static function getById($id) {
		$q = Doctrine_Query::create()
			    ->from('Field f')
			    ->leftJoin('f.Matches m')
			    ->where('f.id = ?', $id)
			    ->orderBy('m.scheduledTime ASC');
		$field = $q->fetchOne();
		return $field;
	}
	
	public static function getList($tournamentId) {
		$q = Doctrine_Query::create()
			    ->from('Field f')
			    ->where('f.tournament_id = ?', $tournamentId)
			    ->orderBy('f.title ASC');
		return $q->execute();
	}

}