<?php

/**
 * Field
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Field extends BaseField {
	
	public static function getFieldIdByNr($fieldNr) {
		// returns the field id of the field called "Field $fieldNr"
		$q = Doctrine_Query::create()
				->select('f.id')
			    ->from('Field f')
			    ->where('f.title = "Field '.$fieldNr.'"');
		FB::log('retrieving field id from nr '.$fieldNr.' using query '.$q->getSqlQuery());
		$fieldId = $q->fetchOne();
		FB::log('got fieldId '.$fieldId['id']);
		
		return $fieldId['id'];		
	}
	
	public static function getById($id) {
		$q = Doctrine_Query::create()
			    ->from('Field f')
			    ->leftJoin('f.Matches m')
			    ->where('f.id = ?', $id)
			    ->orderBy('m.scheduledTime ASC');
		$field = $q->fetchOne();
		return $field;
	}
	
	public static function getList($tournamentId) {
		$q = Doctrine_Query::create()
			    ->from('Field f')
			    ->where('f.tournament_id = ?', $tournamentId)
			    ->orderBy('f.rank ASC, f.title ASC');
		return $q->execute();
	}
	
	public static function getFieldNrFromTitle($fieldTitle) {
		$pos=stripos($fieldTitle,'Field',0);
		if ($pos === false) { return false; }
		return (int)substr($fieldTitle, $pos+5,3);
	}

}