<?php

/**
 * PoolTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PoolTemplate extends BasePoolTemplate {

	
	public static function getList() {
		$q = Doctrine_Query::create()
				->from('PoolTemplate t')
				->leftJoin("t.PoolType pt");
		$templates = $q->execute();
		return $templates;
	}
	
	public static function getById($id) {
		return Doctrine_Core::getTable("PoolTemplate")->find($id);
	}
	
}