<?php

/**
 * PoolRuleset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PoolRuleset extends BasePoolRuleset {
	
	const MANUAL_ID = 1;
	
	
	
	public static function getList() {
		$q = Doctrine_Query::create()
				->from('PoolRuleset t')
				->leftJoin("t.PoolStrategy ps");
		$rulesets = $q->execute();
		return $rulesets;
	}

	public static function getByTitle($s) {
		$q = Doctrine_Query::create()
				->from('PoolRuleset t')
				->where('title = ?', array($s));
		$ruleset = $q->fetchOne();
		return $ruleset;
	}
}