<?php

/**
 * Round
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Round extends BaseRound {

	public function allTeamsFilledIn() {
		// returns true if all teams of all matches of this round are filled in
		// i.e. the matchups have been created
		foreach($this->Matches as $match) {
			if (is_null($match->home_team_id) || is_null($match->away_team_id)) {
				return false;
			}
		}		
		return true;		
	}
	
	public function allResultsFilledIn() {
		// returns true if all results of all matches of this round are filled in
		foreach($this->Matches as $match) {
			if (is_null($match->homeScore) || is_null($match->awayScore)) {
				return false;
			}
		}		
		return true;
	}
	
	public function randomScoreFill() {
		foreach($this->Matches as $match) {
			if (is_null($match->homeScore)) {
				$match->homeScore=rand(0,15);
				$match->save();				
			}
			if (is_null($match->awayScore)) {
				$match->awayScore=rand(0,15);
				$match->save();
			}
		}
	}
	
	public static function deleteRounds($poolId) {
		$rounds = Round::getRounds($poolId);
		foreach($rounds as $round) {
			foreach($round->Matches as $match) {
				$match->delete();
			}
			$round->delete();
		}
	}
		
	public static function getRounds($poolId) {
		FB::error('maybe this does not work, we should fetchOne instead of execute');
		$q = Doctrine_Query::create()
			    ->from('Round r')
			    ->leftJoin('r.Matches m')
			    ->leftJoin('m.HomeTeam ht')
			    ->leftJoin('m.AwayTeam at')
			    ->leftJoin('m.Field f')
			    ->where('r.pool_id = ?', $poolId)
			    ->orderBy('r.rank ASC, m.rank ASC');
		return $q->execute();
	}

	public static function getRoundByRank($poolId, $roundRank) {
		$q = Doctrine_Query::create()
			    ->from('Round r')
			    ->leftJoin('r.Pool p')
			    ->leftJoin('r.Matches m')
			    ->leftJoin('m.Field f')
			    ->leftJoin('m.HomeTeam ht')
			    ->leftJoin('m.AwayTeam at')
			    ->where('r.pool_id = "'.$poolId.'" AND r.rank = "'.$roundRank.'"')
			    ->orderBy('m.rank ASC');
//	    echo "<br> SQL:" . $roundRank . " <br> ". $q->getSqlQuery() ."</br>";
		return $q->fetchOne();
	}

	public static function getRoundById($roundId) {
		$q = Doctrine_Query::create()
			    ->from('Round r')
			    ->leftJoin('r.Matches m')
			    ->where('r.id = "'.$roundId.'"')
			    ->orderBy('m.rank ASC');
		return $q->fetchOne();
	}
	
}