<?php

/**
 * Stage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Stage extends BaseStage{

	
	public function schedule($teamCount) {
		foreach($this->Pools as $pool) {
			if($teamCount > 0) {
				$teamCount -= $pool->schedule($teamCount);
			}else{
				break;
			}
		}		
	}
	
	public function getTeamCount() {
		$result = 0;
		foreach($this->Pools as $pool) {
			$result += $pool->getTeamCount();
		}
		return $result;
	}
	
	public function getQaulifiedTeamCount() {
		$result = 0;
		foreach($this->Pools as $pool) {
			$result += $pool->getQualifiedTeamCount();
		}
		return $result;
	}
	
	public static function getById($id) {
		$q = Doctrine_Query::create()
			    ->from('Stage s')
			    ->leftJoin('s.Division d')
			    ->leftJoin('s.Pools p')
			    ->where('s.id = ?', $id);
		$stage = $q->fetchOne();
		return $stage;
	}
	
}