<?php

/**
 * Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Team extends BaseTeam {
	
	
	
	public function joinedMatches() {
		$result = array();
		foreach($this->HomeMatches as $match) $result[] = $match;
		
		foreach($this->AwayMatches as $match) {
			for($i = 0; $i < count($result); $i++) {
				$found = false;
				if($match->scheduledTime <= $result[$i]->scheduledTime) {
					array_splice($result, $i, $match);
					$found = true;
					continue;
				}
			}
			if(!$found) {
				$result[] = $match;
			}
		}
		return $result;
	}
	
	public static function teamNameExists($divisionId, $teamName) {
		// checks if a team with name $teamName exists in $divisionId
		FB::group('checking if '.$teamName.' exists in division '.$divisionId);
		$q = Doctrine_Query::create()
				->from('Team t')
				->where('t.division_id = ?',$divisionId)
				->andWhere('t.name = ?', $teamName);
		$team = $q->fetchOne();
		FB::groupEnd();
		return $team;
	}
	
	public static function getTeamsWithoutPoolForDivision($divisionId) {
		$q = Doctrine_Query::create()
				->from('Team t')
				->leftJoin("t.PoolTeam pt")
				->where('t.division_id = ? AND pt.pool_id is null', $divisionId);
		$teams = $q->execute();
		return $teams;
	}

	
	public static function getExtendedTeamById($id) {

		$q = Doctrine_Query::create()
			    ->from('Team t')
			    ->leftJoin('t.HomeMatches hm')
			    ->leftJoin('t.AwayMatches am')
			    ->leftJoin('hm.Field hf')
			    ->leftJoin('am.Field af')
			    ->leftJoin('t.SMSs sms')
			    ->leftJoin('sms.Round sr')
			    ->leftJoin('sr.Pool srp')
			    ->where('t.id = ?', $id)
			    ->orderBy('hm.scheduledTime ASC, am.scheduledTime ASC');
		$team = $q->fetchOne();
		
		
		return $team;
	}
	
}