<?php

/**
 * Tournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament extends BaseTournament {
	
	const STATE_OPEN = 1;
	const STATE_ACTIVE = 2;
	const STATE_CLOSED = 3; 
	

	
	public static function getList() {
		$q = Doctrine_Query::create()
			    ->from('Tournament t')
			    ->orderBy('t.startDate DESC, t.title ASC');
		return $q->execute();
	}
	
	public static function getById($id) {
		$q = Doctrine_Query::create()
			    ->from('Tournament t')
			    ->leftJoin('t.Divisions d')
			    ->where('t.id = ?', $id);
		$tournament = $q->fetchOne();
		return $tournament;
	}

}